name: Update Data

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: Ubuntu-20.04

    steps:
      - uses: docker://alpine/httpie:latest
      - run: curl -X POST https://vpn-gate-api.now.sh
