name: Update Data

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker://alpine/httpie:latest
      - run: curl -X POST https://vpn-gate-api.now.sh
